### ISSUE TITLE
Could not compile `tealr_derive`

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [lenscas/tealr#80] opened 2023-06-10 05:28 UTC
I'm making a bevy game that uses `bevy_mod_scripting`, which uses this crate. When I try to build my game, it spits out this linking error: https://gist.github.com/JohnTheCoolingFan/3e4ae02a70dcd94d6925dbdc73e4832e

The game source is available here: https://github.com/JohnTheCoolingFan/scriplets/tree/experiments

**Comment by lenscas** [comment] 2023-06-10 08:07
I am not entirely sure what happened here. I tried building the project manually and it compiled tealr and tealr_derive fine.

I suggest to do run `cargo clean` and see if that fixes things, otherwise make sure you either use tealr's `vendored` feature or that you have a lua install that you can link against.

**Comment by JohnTheCoolingFan** [comment] 2023-06-10 10:16
I've done a `cargo clean` and tried building again, same result. `bevy_mod_scripting` uses vendored lua by default I think

**Comment by lenscas** [comment] 2023-06-10 10:54
Sorry. I've never seen this error before and as mentioned above it isn't an error I can reproduce.

I think it is somehow related to bzip. You could try turning off the default features from tealr and see how it goes. Make sure that bevy_mod_scripting doesn't turn them on.

**Comment by saethlin** [comment] 2023-06-10 14:42
This is probably a compiler bug, see https://github.com/rust-lang/rust/issues/111888#issuecomment-1585690896

(you would be justified in closing this issue)

**Comment by lenscas** [comment] 2023-06-10 16:41
Thanks everyone for looking into it. It sounds like something that would've been a nightmare to figure out otherwise.

I am going to keep this issue open until the next version of Rust gets released (which presumably/hopefully fixes this) just to make this issue easy to find.

Again, huge thanks for figuring it out. Saved me a decent headache :tada:

**Comment by lenscas** [comment] 2023-07-13 14:20
seems the issue is still open but I think this one has been open for long enough. So, going to close it. Rustc will probably be able to get it fixed, hopefully sooner rather than later.

**Closed by lenscas** 2023-07-13 14:20 UTC
