### ISSUE TITLE
using serde and tealr in the same derive

### ISSUE THREAD

**Issue by knassar702** [lenscas/tealr#75] opened 2023-01-11 09:39 UTC
Hello, I'm trying here to use enum from lua and this enum values would be formatted in json from the rust program but the main problem here is I cannot use the serde to convert the enum to json or using tealr to make it usable from lua side at the  same time

```rust
use tealr::{mlu::FromToLua, TypeName};
use serde::{Deserialize, Serialize};

#[derive(Clone,FromToLua, TypeName ,Deserialize, Serialize)]
#[serde(untagged)]
#[tealr(creator_name = MatcherCreator)]
pub enum ReportMatchers {
    RawRequest(String),
    RawResponse(String),
    RequestHeaders(String),
    ResponseHeaders(String),
    ResponseBody(String),
    RequestBody(String),
}
```

**Comment by knassar702** [comment] 2023-01-11 10:58
Hey @lenscas , I got this error when I tried to compile it 

```rust
error: cannot find attribute `serde` in this scope
  --> src/lua/output/cve.rs:25:3
   |
25 | #[serde(untagged)]
   |   ^^^^^
   |
   = note: `serde` is in scope, but it is a crate, not an attribute
```

**Comment by lenscas** [comment] 2023-01-11 11:47
Oh. Weird. Guess I am not handling tags from other crates properly, i would need to look into that.

However in this case I don't even get how this enim can be untagged as they all only contain strings. I have the feeling that this won't do what you want even if I would handle the tag correctly

**Comment by lenscas** [comment] 2023-01-11 13:45
The bug is caused by https://github.com/lenscas/tealr/blob/master/tealr_derive/src/from_to_lua.rs#L453

It should filter out attributes that aren't supported.

**Comment by lenscas** [comment] 2023-01-21 14:38
Should be fixed by #76

**Comment by lenscas** [comment] 2023-03-08 08:44
I am going to close this and assume it is fixed. Feel free to reopen if it is not

**Closed by lenscas** 2023-03-08 08:44 UTC

**Comment by knassar702** [comment] 2023-05-14 00:47
Hi @lenscas, sorry for not noticing the notification about this problem earlier. I've tested your changes and everything seems to be working properly now. Thank you for your hard work and effort :)
